### ISSUE TITLE
Downloading at 128kbps

### ISSUE THREAD

**Issue by Braverinho** [pranjalagg/spdl#20]
Hello, yesterday i was using this tool and everything went perfect, but today i started downloading tracks / playlists once again and .mp3 files are being downloaded at a 128kbps bitrate.

Does anyone have a solution for this? or any ideas on why this is happening?

TIA

**Comment by itssKieron** [comment]
Also having the same issue.

**Comment by starcrash-13** [comment]
Same here.

Edit: Just checked and this is also happening on spotifydown.com.

**Comment by Braverinho** [comment]
> Same here.
> 
> Edit: Just checked and this is also happening on spotifydown.com.

So no more 320kbps until spotifydown.com fixes it?

**Comment by itssKieron** [comment]
> > Same here.
> 
> > 
> 
> > Edit: Just checked and this is also happening on spotifydown.com.
> 
> 
> 
> So no more 320kbps until spotifydown.com fixes it?

Yeah it could be an issue, it's a shame as this is the only no BS downloaded and using CLI just makes it so much easier. I use it to import playlists for DJ sets.

**Comment by pranjalagg** [comment]
It happened a few days ago too, but 320kbps was back on spotifydown.com after a few days. Hopefully, it will return again this time

**Comment by pranjalagg** [comment]
I have added a feature where the lower bitrate tracks are separated into a different folder automatically. So that means, when you run the command, if the API is responding with 128kbps songs, those will be separated from the 320kbps songs. And later, if you decide to try downloading those tracks again, you can remove the lower bitrate ones and at once.
