### ISSUE TITLE
Progress and config

### ISSUE THREAD

**Issue by mdeeter** [pranjalagg/spdl#29]
@pranjalagg

I've made a few updates in a local branch 
... to show the progress of the downloads.
... to load default values from a config file.

If you're interested... otherwise, I'll just fork it.  I don't have access to create a pull request... I can create one for each feature for you to review and approve/reject, if you like.

<video src="https://github.com/user-attachments/assets/ae49e500-d26d-4d89-8dfa-4fa37f61afc9"/>

**Comment by pranjalagg** [comment]
@mdeeter This looks great. I would love a PR for this. I haven't set any restrictions for someone to raise a PR, but let me know if you are not able to.

Also, what default values are you loading? The output directory and naming convention?

**Comment by mdeeter** [comment]
When I try to push up a new branch for a PR, I get this error:
![image](https://github.com/user-attachments/assets/59812605-6616-45bb-90a3-55b32cfb9a50)

**Comment by pranjalagg** [comment]
You would have to first fork this repo to your account and push your changes in a branch to the forked repo. From there a PR can be raised to this repo.

Example:
After forking, you push your changes to a branch called `feature_show_progress`.  Now, a PR can be raised like so `pranjalagg/spdl/main <- mdeeter/spdl/feature_show_progress`.

It is not allowing you to directly push to this repo, because you are not the owner or collaborator. This is how GitHub works by design unfortunately.

**Comment by mdeeter** [comment]
ah, gotchya... I haven't contributed to other repos (where I wasn't a contributor) before... I'll create a fork and go from there.

**Comment by pranjalagg** [comment]
No worries. Thanks!
